spring.application.name=CaloriesApp
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/calories_app_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false